"""First-digit scoring for residual patching. Only the prompt is patched, so digits after the first are
generated by the base model's own layers 0-20 and drift; the first answer token is the clean readout."""

import json
import sys
from pathlib import Path

RUN = Path(sys.argv[1] if len(sys.argv) > 1 else "artifacts/patch_target_residuals")


def first_digit(n: int) -> str:
    return str(n)[0]


def main():
    rows = [json.loads(l) for l in (RUN / "predictions.jsonl").open()]
    pairs = {(r["a"], r["b"]) for r in rows}
    shared = sum(first_digit(a + 3 * b - 7) == first_digit(a * b) for a, b in pairs) / len(pairs)
    print(f"pairs where secret and product share a first digit: {shared:.3f}")
    report = {"shared_first_digit_rate": shared}
    print(f"{'condition':10} {'=secret 1st':>11} {'=product 1st':>12} {'secret-only 1st':>15}")
    for scope in ("last", "all"):
        for layer in sorted({r["layer"] for r in rows}):
            rs = [r for r in rows if r["scope"] == scope and r["layer"] == layer]
            got = [r["raw"].strip()[:1] for r in rs]
            sec = [first_digit(r["a"] + 3 * r["b"] - 7) for r in rs]
            prod = [first_digit(r["a"] * r["b"]) for r in rs]
            distinct = [(g, s) for g, s, p in zip(got, sec, prod) if s != p]
            stats = {
                "first_eq_secret": sum(g == s for g, s in zip(got, sec)) / len(rs),
                "first_eq_product": sum(g == p for g, p in zip(got, prod)) / len(rs),
                "first_eq_secret_where_distinct": sum(g == s for g, s in distinct) / len(distinct),
            }
            report[f"{scope}|L{layer}"] = stats
            print(f"{scope + '|L' + str(layer):10} {stats['first_eq_secret']:11.3f} {stats['first_eq_product']:12.3f} "
                  f"{stats['first_eq_secret_where_distinct']:15.3f}")
    (RUN / "first_digit.json").write_text(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
